---
name: "workflow using docker action"
on:
  push:
    branches:
      - main

jobs:
  greet-user:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run docker action
      uses: ./docker_action
      with:
        message: "Hello from docker action"
