name: "workflow example remote"
on:
  push:
    branches:
      - main

jobs:
  greet-user:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Greet user
      uses: ttych/meet_github_actions_custom/simple_greet@main
      with:
        username: "Jean"
        greeting: "Deer"
